### ISSUE TITLE
[Chpater 4] 멀티코어 아키텍처에서 병렬로 실행할 수 있다.

### ISSUE THREAD

**Issue by kiki-sati** [java-express/modern-java-in-action#11]
![스크린샷 2022-09-13 21 31 18](https://user-images.githubusercontent.com/83346234/189902851-b8f9574c-fecc-4484-a038-de555206d34a.png)

**Chapter 4 - 스트림 소개 (p.137)**

`stream()을 parallelStream()으로 바꾸면 이 코드를 멀티코어 아키텍처에서 병렬로 실행할 수 있다.`
위의 대목에서 멀티코어 아키텍처에서 병렬로 실행할 수 있다는게 어떤 의미인지 궁금합니다.

**Comment by jaeminkim90** [comment]
@kimrumm
일단 질문에 대한 답부터 드립니다.

제 생각에 `멀티코어 아키텍처`란, ~~`parallelStream()`을 사용했을 때 **작업이 병렬로 처리될 수 있도록 설계된 내부 구조**라고 이해하시면 될 거 같습니다. 즉, `parallelStream()`의 **내부 로직**이라 할 수 있겠네요. 병렬 작업을 위해 만들어진 설계(=멀티코어 아키텍처) 라고 이해하셔도 무방할 거 같습니다.~~

그냥 단순하게 멀티코어를 가진 하드웨어 환경으로 이해해도 될 거 같아요. 다시 생각해보니 이게 맞는거 같습니다.

하지만 아마도 질문을 올리신 배경에는 아래와 같은 궁금증이 있으셨을 거 같습니다. 이에 대해 알아본 내용을 추가하도록 하겠습니다. 

- 그래서 병렬 작업을 위해 만들어진 설계라는 것이 구체적으로 뭐냐?
- 내부 동작을 비교할 때, parallelStream()과 일반 Stream()는 어떤 차이가 있냐? 

저도 좀 찾아보고나서 알게 되었는데, 책에서 설명하는 병렬 처리에 대한 개념적 설명이 그다지 친절하지 않았던거 같습니다. `parallelStream()`의 병렬 처리가 어떤 의미를 가지는지 이해하기 위해서는 싱글 코어 시대의 병렬 처리와 멀티 코어 시대의 병렬 처리에 대한 차이를 구분해보면 좋습니다.

일단 코어와 스레드를 개념적 차이를 알아야합니다. 멀티 스레드 방식의 병렬 처리라고만 하면, 싱글 코어를 사용한 병렬 처리인지 멀티 코어를 활용한 병렬 처리인지 알기 어렵습니다. 싱글 코어 시대에서도 멀티 스레딩이란 개념이 있었기 때문에표현이 애매합니다.

코어는 하드웨어 관점에서 CPU의 논리 연산을 처리하는 물리적 자원입니다. 반면 스레드는 소프트웨어 관점에서 논리적인 작업을 처리하는 단위라고 볼 수 있습니다. 멀티 스레드라 하면, 소프트웨어 관점에서 작업을 나누어 처리한다고 볼 수 있습니다. 이때 작업이 처리되는 물리적 자원이 싱글 코어일 수도 있고, 멀티 코어일 수도 있습니다. 스레드 관점에서만 보면 하나의 코어 안에서 4개의 스레드가 동작하는 것과 4개의 코어 안에서 4개의 스레드가 각각 동작하는 것 모두 멀티 스레딩이기 때문입니다. 

그렇다면 병렬 처리란 구체적으로 어떤 개념일까요? 병렬 컴퓨팅의 기본 개념은 여러 개의 연산을 처리할 때 그 연산 작업들이 서로 의존성이 없다면 기다리지않고 동시에 작업을 수행하는 것을 의미합니다. 병렬화의 과정은 동시에 처리가 가능한 작업을 찾는 것에서 시작되며, 나눠져 처리된 작업이 합쳐진 후 종료됩니다. 즉 작업 단위인 스레드를 쪼개고, 나누어 처리한 다음 다시 모으는 것입니다.

chapter1에서도 설명이 나오지만, 싱글 코어 시대에서는 하나의 물리적 하드웨어 안에서 멀티 스레드를 동작시키는 방식의 동시성을 사용했습니다. 동시성은 논리적인 개념의 병렬 처리이며 엄밀하게 말하자면 `동시에 실행되는 것 같이 보이는 작업` 입니다. 빠른 작업 변경(Context Switching) 방식을 사용하여 마치 두 작업이 동시에 처리되는 것처럼 보이지만, 사실 순차적으로 작업이 처리된다고 보시면 됩니다. 반면, 멀티 코어 시대에서는 다수의 코어를 이용하는 스레드 병렬이 가능해졌습니다. 물리적 개념의 병렬적 자원 처리가 가능해졌으며, 실제로 동시에 여러 작업이 처리됩니다. 멀티 코어에서 멀티 스레드를 동작시키기 때문입니다. 아래 이미지를 참고하시면 이해하는데 도움이 될 거 같습니다. `순차적 작업`, `동시성 작업`, `병렬 작업`을 비교한 이미지입니다. 여기서 동시성 작업이 싱글 코어에서의 멀티 스레딩이라고 보시면 됩니다.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/48195881/190150537-4fcf69d7-ba02-4562-b70e-1345b9887599.png">

<img width="419" alt="image" src="https://user-images.githubusercontent.com/48195881/190150550-163cd81d-86d3-4c46-8d5f-96c41c054822.png">

멀티 코어 환경에서 멀티 스레딩을 사용하는 것이 진정한 병렬 처리라는 것이 이해되시나요? 
병렬 컴퓨팅을 소프트웨어 상에서 컨트롤하기 위해서는 

1. 병렬 작업이 가능하도록 멀티 스레드를 생성하고
2. 각 스레드를 멀티 코어에 분배해야 합니다. 

바로 이 역할을 `parallelStream()`의 내부 구조에서 처리합니다. 멀티 코어를 활용한다는 점에서 싱글 코어를 사용하는 멀티 스레딩 방식(정확히는 동시성)과는 다르다고 할 수 있습니다. 

음..근데 실제 parallelStream()가 어떤 로직으로 멀티 코어를 탐색하고 적절한 스레드를 생성하여 작업을 수행하는지는 저도 잘 모릅니다. 내부적으로 ForkJoinPool 프레임워크를 사용하며,  Runtime.getRuntime().availableProcessors()에서 리턴된 값으로 쓰레드 풀을 구성한다는 정도는 찾아봤는데 자세히는 모릅니다. 나중에 JVM을 깊이있게 공부할 기회가 생긴다면 그때 공부해봐야 할 거 같습니다.

아무튼, parallelStream()을 이용하면 하드웨어 자원까지 쉽게 컨트롤할 수 있다는 점 때문에 책에서는 (큰 노력없이)공짜로 병렬성을 얻을 수 있다고 표현합니다. 하지만, 반대로 멀티 코어 병렬 작업의 특성으로 인해 parallelStream()이 문제를 일으킬 수도 있다는 점을 기억해야합니다.

멀티코어 병렬 작업은 하드웨어 자원을 탐색하고 그에 맞게 스레드가 쪼개져야만  작업이 가능하므로, 데이터 자체가 명확하게 스레드 분할이 가능한 구조여야 합니다. 대표적으로 스트림의 소스가 ArrayList, HashMap, HashSet, ConcurrentHashMap의 인스턴스이거나, 배열, int 범위, long 범위일 때 병렬화의 효과가 가장 좋다고 하네요. 그리고 데이터의 크기가 클 때 효율이 좋습니다. 이러한 소스의 특징은 데이터를 원하는  크기로 나눠서 다수의 스레드로 분배하기 좋다는 특징이 있습니다. 반대로 데이터 크기가 작으면 오히려 부가적인 작업에 사용되는 자원으로 인해 속도가 더 저하됩니다. 

병렬 처리라는 것은 작업을 쪼개서 처리하기 때문에 많은 양의 연산을 처리할 때는 분명 이점이 있을 겁니다. 하지만 반대로 작업을 쪼개는 데 필요한 오버헤드와 콘텍스트 스위칭이 있고,  작업 후 분할된 연산 결과를 다시 취합하는 과정도 자원으로 사용됩니다. 또한 병렬 처리 특성상 순서를 보장하지 않음으로 순서의 연관성이 있는 공유 가변 자원을 사용한다면 예상하지 못한 결과가 나올 수 있습니다. 따라서 순서 보장이 필요하거나, 컬렉션 사이즈가 작은 경우 parallelStream()의 병렬 처리 방식을 적합하지 않을 수 있습니다.

그렇다면 Stream은 어떨까요? 기본적으로 Stream은 순차 Stream입니다. 컬렉션과 마찬가지로 순차적으로 값에 접근합니다. 하지만 개발자가 임의로 병렬 스트림으로 전환할 수도 있죠!(= parallelStream)

![image](https://user-images.githubusercontent.com/48195881/190150240-3bb65a10-3215-44e2-b8e2-46bcbecee4aa.png)
