### ISSUE TITLE
[Chapter4] 고수준 빌딩 블록, 스레드와 락 

### ISSUE THREAD

**Issue by kimjinwook1** [java-express/modern-java-in-action#12]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/87925272/190395980-62b47f6a-eba2-40b2-ac91-6c598275824b.png">

p.138 내용 중에 `filter 같은 연산은 고수준 빌딩 블록(high-level building block)으로 이루어져있으므로` 라고 쓰여있는데 **고수준 빌딩 블록**이라는 것이 무엇인지 궁금합니다.

그리고 `결과적으로 우리는 데이터 처리 과정을 병렬화하면서 스레드와 락을 걱정할 필요가 없다`라는 구문에서 왜 스레드와 락을 걱정할 필요가 없는지도 궁금합니다!

**Comment by jaeminkim90** [comment]
`고수준 빌딩 블록`이란 표현은 내부 구조 신경쓰지 않고 사용할 수 있는 스트림 연산 모듈이라고 이해할 수 있을 거 같습니다.

`고수준(high-level)`이라는 의미는 내부 로직을 직접 조작하는 방식이 아니라, 사람이 사용하기 더 편하게 추상화되어있는 인터페이스의 형식을 의미하는 거 같습니다. 프로그래밍 언어를 고수준 언어와 저수준 언어로 나눌 때, 고수준 언어는 하드웨어에서 높은 추상화 단계를 제공하는 인간 친화적인 언어라고 할 수 있습니다. 반대로 저수준 언어라 하면 추상화가 덜 되어 기계에 더 친화적인 언어라고 할 수 있죠. 스트림의 중간 연산을 담당하는 각 메서드들도 내부 로직을 직접 제어하지 않은 높은 수준의 추상화를 제공합니다. 그래서 `고수준`이라는 키워드를 사용한 거 같습니다.

`빌딩 블록(building block)`은 연결해서 하나로 만들수 있는(building) 구조체(block)정도로 해석할 수 있을 거 같습니다. 쉽게 말해 기차를 구성하고 있는 각각의 객실같은 구조라 할 수 있습니다. 기차의 각 칸은 앞 뒤가 똑같은 연결 구조를 가지고 있기 때문에 순서에 상관없이 연결할 수 있습니다. 아래 이미지를 보시면 스트림의 중간 연산도 기차처럼 이어 붙일 수 있습니다.

![image](https://user-images.githubusercontent.com/48195881/190670087-9a194934-2bc3-4bd1-9cf9-06c8046b8c90.png)

정리하면 filter, sorted, map와 같은 중간 작업(intermediate operation) 메서드는 추상화되어 있으며,  동일한 리턴 타입을 갖기 때문에 순서에 상관없이 파이프라이닝(연결해서 붙일 수 있음)이 가능합니다. 그러한 특징을 고수준의 빌딩 블록으로 이루어져 있다고 표현한 거 같습니다. 

그런데 collect는 스트림으로 결과 값을 만들어내는 터미널 작업에 해당하는데 왜 예시에 포함하고 있는지는 잘 모르겠네요. 기차의 맨 끝 칸과 같은 역할을 하기 떄문일까요?

아무튼 스트림의 작업 흐름을 생성, 가공, 결과로 나누었을 때, 가공에 해당하는 메서드를 직접 살펴보면 모두 Stream을 리턴하는 것을 알 수 있습니다. 동일하게 스트림을 다른 스트림으로 변환하는 구조를 갖고 있으므로, 블럭처럼 연결하여 사용할 수 있습니다. 즉 아웃풋이 다시 인풋이 되는 구조라고 할 수 있습니다. => 고수준 빌딩 블럭

참고하실 수 있도록 중간 연산에 해당하는 메서드 시그니처를 아래에 첨부합니다.

```java
Stream<T> filter(Predicate<? super T> predicate);
```

```java
<R> Stream<R> map(Fucntion<? super T, ? extends R> mapper);
```

```java
Stream<T> sorted();

Stream<T> sorted(Comparator<? super T> comparator);
```


스레드와 락을 걱정할 필요가 없다는 말은 그냥 단순하게 있는 그대로 독해해도 될 거 같습니다. 
병렬 처리 과정에서 여러 스레드가 동일한 클래스에 접근할 때 스레드 안전성(Thread-Safe)을 잘 제어해야 하는데, 이전에는 개발자가 Synchronized를 이용해 스레드에 lock을 걸어 동시성을 제어했다면 병렬 방식의 스트림을 사용할 경우 스레드와 락 관리를 직접 할 필요가 없다는 의미 같습니다. 아마 parallelStream을 말하는 것 같은데 parellelStream을 사용하면 스레드 풀에서 할당받은 스레드를 분할하여 사용하고, 필요한 경우 스레드 lock 상태를 컨트롤 한다고 합니다. 말그대로 신경 쓸게 없는 것이죠! :)
