### ISSUE TITLE
[Chapter4] 연산 파이프라인은 데이터 소스에 적용하는 데이터베이스 질의와 비슷하다. 

### ISSUE THREAD

**Issue by parks38** [java-express/modern-java-in-action#13]
파이프라인 구조일 경우 연속된 연산을 하나씩 수행하는 구조라고 이해하고 있는데
데이베이스 질의와 비슷하다는 의미는 질의 어의 하나씩 연산을 순서대로 처리하는 방식과 비슷하다는 것의 의미하는것일지 궁금합니다.

**Comment by jaeminkim90** [comment]
@parks38 맥락을 좀 파악하고 싶은데, 혹시 책 본문에 관련 내용이 있다면 페이지 남겨주세요~

**Comment by parks38** [comment]
> @parks38 맥락을 좀 파악하고 싶은데, 혹시 책 본문에 관련 내용이 있다면 페이지 남겨주세요~

@jaeminkim90  p.141 쪽에 있습니다! 스트림의 두 가지 중요한 특징에 대해서 얘기하며 그중 `파이프라이닝` 설명하는 부분입니다.

**Comment by jaeminkim90** [comment]
제 생각에는 Stream이 가진 선언형 프로그래밍의 특징이 SQL과 비슷하다는 이야기를 하는 거 같습니다.
141page에 스트림의 중요한 2가지 특성으로 소개된 내용(파이프라인, 내부 반복)은 SQL의 특징이기도 합니다.

책에서도 여러번 나오는 내용이지만 Stream은 for문처럼 로직이 외부로 드러나는 명령형 프로그래밍이 아닙니다. map, filter, sort, reduce같은 기본 함수를 조합해서 원하는 동작을 선언적으로 구현할 수 있습니다. 동시에 생성, 가공, 결과로 작업 흐름이 구분됩니다.

아시다시피 SQL도 동작 방식이 비슷합니다. 기본적으로 높은 수준의 추상화를 제공하는 선언형 프로그래밍입니다. 그리고 집합 생성, 가공, 결과의 작업 흐름을 갖습니다. 예를 들어 SQL에서 FROM 절은 논리적으로 다른 모든 절보다 앞에 위치합니다. 하나의 테이블에서 튜플 집합을 생성하는 데 사용됩니다. Stream.of()가 비슷한 역할을 한다고 볼 수 있습니다. 스트림의 파이프라이닝을 형성하는 메서드들과 SQL의 명령어를 비교한 이미지를 참고해보시면 좋을 거 같습니다. 메서드의 위치와 기능이 유사하다는 것을 확인할 수 있습니다.

![image](https://user-images.githubusercontent.com/48195881/190680258-3cf1381b-e44a-4b1a-bbce-5e7224299738.png)

SQL은 데이터베이스가 만족해야할 관계적 제약만 명시하면 결과를 확인할 수 있다는 점에서 훨씬 높은 추상화 수준을 제공하지만, Stream 역시 메서드 조합을 통해 파이프라이닝을 선언적으로 구현할 수 있습니다. 이러한 공통점 때문에 데이터베이스 질의와 비슷하다고 설명한 거 같습니다.

쉽게 말해 SQL처럼 선언적 명령 모음을 조립하여(=파이프라이닝) 원하는 결과를 만들어 낼 수 있다는 뜻으로 이해하셔도 좋을 거 같습니다. :)
