### ISSUE TITLE
[Chapter 6] Characteristics 메서드

### ISSUE THREAD

**Issue by kimjinwook1** [java-express/modern-java-in-action#16]
**p.229** 에 나오는 `Characteristics` 메서드가 정확히 어떤 역할을 하는지 이해가 되지 않습니다.

스트림을 병렬로 리듀스를 할 때 최적화된 선택을 할 수 있는 힌트를 ENUM을 통하여 제공한다고 보면 될 것 같긴한데 어렵네요,, 🤔
`Characteristics` 메서드의 사용 예시를 부탁드리겠습니다!

**Comment by sonchanwoo** [comment]
```
var test
```

`block`

**bold**

**Comment by sonchanwoo-deleted** [comment]
characteristics포함 supply, combiner등의 메서드들은 `Collector인터페이스 구현체`의 `인스턴스 메서드`입니다.

supply().get()
accumulator.accept()
combiner().apply()
finisher().apply()
characteristics()
등을 어디서 사용할 수 있을지 생각을 해보니

collect()와 같은 메서드 내부에 있을 것이라 생각하였습니다.

collect()는 오버로딩된 메서드 포함 총 2종류가 있습니다.

```
collect(Supplier<R> supplier, BiConsumer<R,? super T> accumulator, BiConsumer<R,R> combiner) {
    R result = supplier.get();

    for (T element : this stream)
        accumulator.accept(result, element);
    return result;
}
```

```
collect(Collector<? super T,A,R> collector) {
     //내용 찾을 수 없음
}
```

첫 번째 collect에는 다행이 api명세가 있어 collect와 같은 연산에서 Collector메서드를 사용함을 알 수 있었습니다.

두 번째 collect에서 5종의 메서드를 모두 사용하는 부분이 있을 것이라 생각하게 되었습니다.

<br/>

```
public class Test {
    public static void main(String[] args) {
        List<String> list = new ArrayList<>(Arrays.asList("a", "b", "c"));
        List<String> result = list.stream().collect(new TolistCollector<String>());
        System.out.println(result);
    }
}

class TolistCollector<T> implements Collector<T, List<T>, List<T>> { 
    @Override 
    public Supplier<List<T>> supplier() { 
        return ArrayList::new;
    }
    @Override 
    public BiConsumer<List<T>, T> accumulator() { 
        return List::add; 
    }
    @Override 
    public Function<List<T>, List<T>> finisher() { 
        System.out.println("hello-finish");
        return Function . identity () ; 
    }
    @Override 
    public BinaryOperator<List<T>> combiner() { 
        return (list1, list2) -> {
            list1 .addAll(list2);
            return list1; 
        }; 
    }
    @Override
    public Set<Characteristics> characteristics() {
        return Collections.unmodifiableSet(EnumSet.of(Characteristics.IDENTITY_FINISH, Characteristics.CONCURRENT));
    }
}
```

교재의 toListCollector 커스터마이징 한 코드를 그대로 가져와서 실험을 하였습니다.
1. EnumSet에서 IDENTIFY_FINISH가 있다면, finisher메서드가 실행되지 않습니다.
2. characteristics의 구현을 비워두면, nullPointerException이 발생합니다.

collect(Collector collector) 메서드 블럭 내부에서 characteristics() 반환 값으로 나머지 4개의 메서드의 동작을 제어하고 있다고 보면 될 것 같습니다.

```
function collect() {
    var charSet =  collector.characteristics();//힌트모음집
    var result = collector.supply().get();//빈 누적자

    collector.accumulator().accept();
    collector.combiner().apply();
    //charSet의 나머지 열거형 값이나 병렬상태, 요구하는 로직에 따른 병렬환경에서의 데이터 처리방식(탐색-병합 순서 등)에 따라
    //위 두 메서드에서도 charateristic값에 따른 제어가 일어날 수 있다고 생각합니다. 

    if charSet not contains IDENTIFY_FINISH
        collector.finish().apply();
}
```

위와 같이요.

charSet의 다른 종류일 경우 및 병렬환경까지 고려한다면 상당히 복잡할 것 같습니다.
(도움이 될지는 모르겠지만 parallelStream으로 하면 combine return문을 비워놓을 시 문제가 발생합니다. 실제 코드는 synchronized, Lock등으로 훨씬 복잡할 것 같습니다.)

collect()의 실제코드를 보고싶었으나, 방법을 모르는지 찾지를 못하여 부족한 설명이라고 생각이 듭니다.

**Comment by kimjinwook1** [comment]
친절한 설명 감사합니다 👍
