### ISSUE TITLE
[Chapter 2] 메서드는 객체만 인수로 받는다

### ISSUE THREAD

**Issue by jaeminkim90** [java-express/modern-java-in-action#5]
> p.74
> 안타깝게도 메서드는 객체만 인수로 받으므로 
<br>

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/48195881/187067006-bdba4387-b2e9-43e4-bebd-3371b0cd4b31.png">

2장에서는 무게와 색을 기준으로 사과를 선별하는 로직을 단계적으로 개션해보면서 람다를 설명해주는 거 같아요. 위에 인용한대로 메서드가 객체만 인수로 받는다면 람다도 내부적으로는(혹은 실제로는) 메서드 시그니처에 따라 인스턴스를 생성하고 인수로 객체를 전달하는 건가요?

**Comment by kimrumm** [comment]
`Chapter3 - 람다 표현식, p.94` 에서 찾아보니 함수 디스크립터가 있어서 가져왔습니다. 

![IMG_399BBC6ADF1B-1](https://user-images.githubusercontent.com/83346234/187927819-292dd4fe-cabf-4e46-9e93-806f791e4149.jpeg)


아래는 람다의 내부동작에 대해 작성한 블로그 글이 있어서 참고용으로 링크 첨부하였습니다!
[람다의 내부동작 #1](https://tourspace.tistory.com/11?category=788398)
[람다의 내부동작 #2](https://tourspace.tistory.com/12?category=788398)

질문주신 부분에 대해 이해가 잘 되지 않아서, 책과 블로그 글을 첨부하였습니다.
질문 주셨던거와 제가 답변한 부분에 대해 다르다면 말씀해주세요!

**Comment by kiki-sati** [comment]
`Chapter3 - 람다 표현식, p.94` 에서 찾아보니 함수 디스크립터가 있어서 가져왔습니다. 

![IMG_399BBC6ADF1B-1](https://user-images.githubusercontent.com/83346234/187927819-292dd4fe-cabf-4e46-9e93-806f791e4149.jpeg)


아래는 람다의 내부동작에 대해 작성한 블로그 글이 있어서 참고용으로 링크 첨부하였습니다!
[람다의 내부동작 #1](https://tourspace.tistory.com/11?category=788398)
[람다의 내부동작 #2](https://tourspace.tistory.com/12?category=788398)


`람다도 내부적으로는(혹은 실제로는) 메서드 시그니처에 따라 인스턴스를 생성하고 인수로 객체를 전달`

이라는 키워드로 찾아보았는데,
질문 주셨던 거와 제가 답변한 부분에 대해 다르다면 말씀해주세요!
