### ISSUE TITLE
[Chapter 2] 인터페이스의 추상 메서드가 2개인 경우 람다를 이용한 동작 파라미터화 방법이 있나요?

### ISSUE THREAD

**Issue by jaeminkim90** [java-express/modern-java-in-action#6]
> p.82
> List<Apple> redApples = filter(inventory, (Apple apple) -> RED.equals(apple.getColor()));

<br>
<img width="921" alt="image" src="https://user-images.githubusercontent.com/48195881/187067431-529441c6-1c88-49e0-a138-b8026481bb54.png">

추상 메서드가 2개인 인터페이스는 람다식으로 구현체를 만들 수 없는건가요? 
<br>

책의 설명대로 filter()의 파라미터 타입에 ApplePredicate 인터페이스를 넣고, 인수에 람다식을 전달해보니 곧 바로 test()의 구현체(Override)로 사용하는 걸 확인했습니다. 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/48195881/187067587-ce6513ac-6d8c-4ffe-a047-40e3e4be61b0.png">
<img width="253" alt="image" src="https://user-images.githubusercontent.com/48195881/187067589-1f67c081-0c6e-4b08-ace9-6c969ba333b9.png">
<img width="843" alt="image" src="https://user-images.githubusercontent.com/48195881/187067635-9ad90652-e915-4ade-9014-19bbd7b02bf3.png">
<img width="863" alt="image" src="https://user-images.githubusercontent.com/48195881/187067637-487f9ff2-4182-46aa-9747-a83ccf795ca2.png">

<br>
지금까지 클래스에서 implements하는 방식으로만 인터페이스를 사용했었는데 람다식으로 바로 구현 메서드를 재정의할 수 있다는 사실이 흥미롭네요. 한 가지 궁금한 점이 생겼는데, 인터페이스에 추상 메서드가 하나인 경우 전달되는 람다식도 하나이기 문제 없이 메소드 재정의(Override) 대상으로 인식할 수 있을 거 같습니다. 그러면 함수형 인터페이스는 두 개 이상의 메서드를 가질 때 어떻게 람다식을 활용할 수 있나요? 오직 1개일 때만 사용할 수 있는 건가요?

**Comment by kiki-sati** [comment]
함수형 인터페이스의 정의에 대해 찾아보니, 
함수형 인터페이스는 (Functional Interface)는 추상 메서드가 단 하나만 존재하는 인터페이스이며,
자바의 람다식은 이러한 함수형 인터페이스를 기반으로만 작성 될 수 있다고 합니다. (하지만 default와 static 메서드의 개수에는 제약이 없습니다.) 그래서 Single Abstract Method (SAM) 이라고 불리기도 합니다. 

**예시**
![image](https://user-images.githubusercontent.com/83346234/187220736-3b79f61c-88ed-49c4-8bd4-36f34ebcb9a5.png)

@FunctionalInterface   
java.lang 이 지원하는 어노테이션입니다. 
이 어노테이션을 활용하면 함수형 인터페이스가 아닌 경우, 컴파일 에러를 발생시켜 좀 더 안전한 코딩을 할 수 있습니다. 
함수형 인터페이스 라는걸 명시해 주지 않으면 일반 인터페이스로 인식해 추후 코드가 꼬여 에러가 발생할 수 있기 때문 입니다. 

![image](https://user-images.githubusercontent.com/83346234/187222172-38398d79-da40-4993-8701-c721b1583910.png)

위처럼 둘 이상의 추상 메서드가 존재하게 되면, 함수형 인터페이스가 아니기 때문에 해당 오류가 발생하는 것을 확인 할 수 있습니다. 

![image](https://user-images.githubusercontent.com/83346234/187222530-cd71b542-4542-4580-8405-b6d04a661273.png)

  **오류 번역(번역기로 돌린거라 어색할 수 있습니다..!)**
> 인터페이스 유형 선언이 Java 언어 사양에 정의된 대로 기능하는 인터페이스임을 나타내는 데 사용되는 유용한 주석 유형입니다. 
> 개념적으로 기능 인터페이스는 정확히 하나의 추상적 방법을 가지고 있습니다. 기본 메서드는 구현이 있기 때문에 추상적이지 않습니다. 
> 인터페이스가 java.lang의 공용 메서드 중 하나를 재정의하는 추상 메서드를 선언하는 경우입니다. 
> 인터페이스의 모든 구현이 java.lang에서 구현되기 때문에 인터페이스의 추상 메서드 수에 계산되지 않습니다.
> 개체 또는 다른 위치입니다. 함수 인터페이스의 인스턴스는 람다 식, 메서드 참조 또는 생성자 참조를 사용하여 만들 수 있습니다.
> 이 주석 유형으로 주석이 달린 형식의 경우 컴파일러는 다음 경우를 제외하고 오류 메시지를 생성해야 합니다.
> 유형은 주석 유형, 열거형 또는 클래스가 아닌 인터페이스 유형입니다. 주석이 달린 유형은 기능 인터페이스의 요구 사항을 충족합니다.
> 그러나 컴파일러는 기능 인터페이스의 정의를 충족하는 인터페이스를 기능 인터페이스로 취급합니다. 인터페이스 주석이 인터페이스 선언에 있습니다.
> 

그래서 함수형 인터페이스는 단 하나의 추상 메서드만 가질 수 있다고 합니다!

**Comment by jaeminkim90** [comment]
상세한 답변 감사합니다! 함수형 인터페이스를 사용할 때는 @FunctionalInterface를 달아주는게 좋겠네요. 컴파일 에러나 코드 분석 측면에서 유용할 거 같아요. 좋은 정보 감사합니다!

**Comment by jaeminkim90** [comment]
오호 책에 예시로 나온 Comparator, Runnable, Callable, EventHandler 모두  @FunctionalInterface를 달아서 명확하게 함수형 인터페이스임을 명시하고 있네요! 

![image](https://user-images.githubusercontent.com/48195881/187889538-76d7eb76-6148-4d0f-99f1-eca9e2a6e483.png)
![image](https://user-images.githubusercontent.com/48195881/187889576-352d2ffd-6772-4ec9-b5a1-cb6c9bca1730.png)
![image](https://user-images.githubusercontent.com/48195881/187889666-570b47f5-3f3f-4dcc-8ed8-ae6a443985b6.png)
![image](https://user-images.githubusercontent.com/48195881/187889980-6544b597-2279-4841-9d89-ab491886e0f6.png)
