### ISSUE TITLE
[Chapter 2] Thread 생성자에 객체만 전달할 수 있었으므로

### ISSUE THREAD

**Issue by jaeminkim90** [java-express/modern-java-in-action#7]
```
p. 84
자바 8까지는 Thread 생성자에 객체만을 전달할 수 있었으므로
```
![image](https://user-images.githubusercontent.com/48195881/187898567-7fa7d5de-8120-4760-81f4-1da67a52252f.png)

이것도 번역 문제인지는 모르겠으나, `자바 8까지는 Thread 생성자에 객체만 전달할 수 있었으므로` 라는 말이 잘 이해가 안되네요. 일반적으로 자바 8까지는 불가하고, 그 이후에 가능하다는 의미로 독해가 되는거 같아서요. 책의 문맥을 고려하면 `자바 8부터는 new Thread()의 인수로 메서드를 넣을 수 있게 되었다`는 의미로 해석되는데.. 그 의미가 맞겠죠? 

참고로 자바 7,8,9 생성자 명세는 객체 타입의 인수만 설명하고 있네요. 아마 람다를 넣어도 실제 파라미터로 전달되는 것은 인스턴스 참조가 맞는거 같아요.

자바 7
![image](https://user-images.githubusercontent.com/48195881/187899656-5d981e1b-8fd5-421d-9502-5d6697f33ffc.png)

자바 8
![image](https://user-images.githubusercontent.com/48195881/187899799-76976979-d7a1-4015-af0a-b08a157e7ae8.png)
 
자바 9
![image](https://user-images.githubusercontent.com/48195881/187899924-8d677a4a-95ca-457d-aa2a-855a6bf62ed4.png)

**Comment by kiki-sati** [comment]
저도 이해가 잘 안되서, 예제 검색 후 가져와봤습니다.

기존에는 첫번째 예제처럼 기존에는 Runnable 인터페이스를 구현한 클래스 객체를 매개변수로 받아서 사용하였지만, 

```java
public class Test implements Runnable {
	@Override
	public void run() {
		int sum = 0;
		for (int index = 0; index < 10; index++) {
			sum += index;
			System.out.println(sum);
		}
		System.out.println( Thread.currentThread() + "최종 합 : " + sum);
	}

	public static void main(String args[]){

		// 기존에는 Runnable 인터페이스를 구현한 클래스 객체를 매개변수로 받아서 사용
		Runnable test = new Test();
		Thread subTread1 = new Thread(test);
		Thread subTread2 = new Thread(test);
		subTread1.start();
		subTread2.start();
	}

}
```

자바 8 이후에는 아래 코드와 같이 익명 구현 객체로 만들어서 간단하게 실행할 수 있다고 하는데,

질문해주신 `자바 8까지는 Thread 생성자에 객체만 전달할 수 있었으므로`
`자바 8부터는 new Thread()의 인수로 메소드를 넣을 수 있게 되었다는 의미로 해석`
부분과 엮어서 어떻게 설명해야 할지 잘 모르겠네요...!! 다른 분 중에서 추가 설명해주실 수 있는 분은 댓글 부탁드립니다!


```java
public class Test2 implements Runnable {
	@Override
	public void run() {

	}

	public static void main(String args[]){
	//익명 구현 객체로 만들어서 간단하게 실행
		Runnable test = new Runnable() {
			public void run() {
				int sum = 0;
				for (int index = 0; index < 10; index++) {
					sum += index;
					System.out.println(sum);
				}
				System.out.println( Thread.currentThread() + "최종 합 : " + sum);
			}
		};
		Thread subTread1 = new Thread(test);
		Thread subTread2 = new Thread(test);
		subTread1.start();
		subTread2.start();
	}

}
```

```java
public class Test2 implements Runnable {
	@Override
	public void run() {

	}

	public static void main(String args[]){
               //람다식을 통한 익명 구현 객체
		Runnable test = ()-> {
			int sum = 0;
			for (int index = 0; index < 10; index++) {
				sum += index;
				System.out.println(sum);
			}
			System.out.println( Thread.currentThread() + "최종 합 : " + sum);
		};

		Thread subTread1 = new Thread(test);
		Thread subTread2 = new Thread(test);
		subTread1.start();
		subTread2.start();
	}


}

```

**Comment by kimjinwook1** [comment]
### 자바 7버전에서 아름님이 작성해주신 테스트 코드 작성해보았습니다.

![image](https://user-images.githubusercontent.com/87925272/188036866-7c4f7a0c-4882-4e6f-86fb-b344f626dc87.png)

![image](https://user-images.githubusercontent.com/87925272/188036886-0f44f3f0-8f1d-410b-8daa-393b95b1a0a0.png)

**애초에 자바 7 에서는 람다를 지원하지 않기 때문에 파라미터로 메서드가 전달되지 않습니다.**

![image](https://user-images.githubusercontent.com/87925272/188037389-b65cccff-5d47-4104-b38a-dc52077089d4.png)


![image](https://user-images.githubusercontent.com/87925272/188037341-08a10e92-29f3-4244-af58-cac024693a68.png)

재민님이 말씀해주신 
> 자바 8부터는 new Thread()의 인수로 메서드를 넣을 수 있게 되었다.

라는 해석이 올바른 해석이 맞는 것 같습니다.

**Comment by kiki-sati** [comment]
> 

감사합니다!!! 이해됐습니다!

**Comment by parks38** [comment]
저 또한 동일한 말이긴 하나 직역하여 올려 보았습니다. 

자바 8 이전에는 객체만 Thread 생성자 안에 인수로 넣을 수 있었기에  void run 메소드가 있는 익명 클래스를 (인수에) 넣는 방법의 패턴이 주로 사용되었습니다. 그 익명 클래스는 Runnable interface 를 implement (상속) 하고 있습니다. 라고 해석하면 될 것 같습니다. 

아름님께서 작성해 주신 `Test implements Runnable` `Test2 implements Runnable`  이 좋은 예시 인 것 같습니다 :)
