### ISSUE TITLE
@FunctionalInterface 간단 소개

### ISSUE THREAD

**Issue by kimjinwook1** [java-express/modern-java-in-action#9]
### @FunctionalInterface

: 함수형 인터페이스임을 가리키는 어노테이션

- 추상 메서드가 두 개 이상이라면 컴파일 에러가 발생한다.
- java.lang.Object의 공용 메서드 중 하나를 재정의 하는 추상메서드를 선언하는 것은 추상 메서드의 수에 포함되지 않는다.
  
  ```java
  @FunctionalInterface
  public interface Comparator<T> {
      
      int compare(T o1, T o2);
  
      boolean equals(Object obj);
  }
  ```
  
- default 메서드 또한 작성 가능하다.
  
  - Java8 부터는 interface에 default 키워드를 통해 메서드를 구현할 수 있다. 또, 이를 구현하는 클래스는interface의 메서드를 @Override 할 수 있다.
    
  
  ```java
  @FunctionalInterface
  public interface Predicate<T> {
  
      boolean test(T t);
  
      default Predicate<T> and(Predicate<? super T> other) {
          Objects.requireNonNull(other);
          return (t) -> test(t) && other.test(t);
      }
  ```

#### 인터페이스

- 모든 멤버변수는 **public static final**이어야 한다. 단, 이를 **생략**할 수 있다.
- 모든 메서드는 **public abstract** 여야 한다. 이 또한 **생략**할 수 있다. 
- 단, **static** 메서드와 **default** 메서드는 **제외**한다.(Java 8 이후)

**Comment by jaeminkim90** [comment]
LGTM 👍

**Comment by kiki-sati** [comment]
TGIF !
